# Generated by Django 4.2.7 on 2025-01-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Um usuário com este e-mail já existe.'}, max_length=255, unique=True, verbose_name='Endereço de e-mail'),
        ),
    ]
